### PR TITLE
(FM-6988) Check for device excluded fields on update

### PR DESCRIPTION
**Pull request by willmeek**

### CODE REVIEW

**Comment by shermdog** [comment]
I think if we're specifying our own `set` then we shouldn't use SimpleProvider.  @da-ar or @DavidS can can confirm.

**Comment by willmeek** [comment]
Good call, removed where we declare our custom setter.

**Comment by tphoney** [comment]
I can see why we need this, it feels like we are potentially missing a trick somewhere. It would be good to get @DavidS or @da-ar to look. It also points towards, if we are not using resource-api simple provider and this is the new trope, maybe we should a centralised version of the set ?

**Comment by DavidS** [comment]
On first impulse I thought this might fit into `canonicalize`, but if I understand this correctly, `safe_update` removes attributes that are not valid to update on a specific target platform version?

That seems a dangerous precedent of ignoring user input.

**Comment by willmeek** [comment]
This looks like the wrong approach. Ideally we should be utilising a custom canonicalise function within the provider, needs the feature added to the netdev type

**Pull request closed without merging**
