### PR TITLE
(maint) Add an OS Family fact

### PR DESCRIPTION
**Pull request by willmeek**
An OS family fact will allow for differentation between IOS
and IOS XE devices

### CODE REVIEW

**Comment by willmeek** [comment]
This may not be needed, our acceptance test Puppet5 does not have device facts

**Comment by Thomas-Franklin** [comment]
> This may not be needed, our acceptance test Puppet5 does not have device facts

Is our acceptance tests not running against latest 5.10.x? Either way I think this is a relevant fact that should still be added.

**Comment by willmeek** [comment]
Our metadata supports 4.7.0 on.

Though I might need to revisit this as code fact/exclusion now I have my first XE-specific field (rather than enum entry)

**Comment by willmeek** [comment]
Yep I need this :D

**Pull request merged**
