### PR TITLE
(maint) Add function to convert values to match type definition

### PR DESCRIPTION
**Pull request by willmeek**

### CODE REVIEW

**Comment by tphoney** [comment]
This does point in the right direction, however i feel we could make this more generic AND role it out everywhere. eg https://github.com/puppetlabs/cisco_ios/blob/master/lib/puppet/provider/ntp_server/ios.rb#L23

`convert_to_type(variable_to_convert, Type)` What do you think, then we can use the same method for dates / integers / whatever.

**Comment by willmeek** [comment]
Good call @tphoney , I'm all for reusable functions. 

This isn't breaking, more a tidyup, I'll park this and revisit after the higher priority work.

**Comment by tphoney** [comment]
WOW WOW WOW, just sooo awesome. i am in awe.

**Comment by tphoney** [comment]
does this remove the need for things like https://github.com/puppetlabs/cisco_ios/blob/79d7dd5cba4e04714dc77e131dbf5474af4194a0/lib/puppet/provider/ntp_server/ios.rb#L25 ???

**Comment by willmeek** [comment]
> does this remove the need for things like
> 
> [cisco_ios/lib/puppet/provider/ntp_server/ios.rb](https://github.com/puppetlabs/cisco_ios/blob/79d7dd5cba4e04714dc77e131dbf5474af4194a0/lib/puppet/provider/ntp_server/ios.rb#L25)
> 
> Line 25 in [79d7dd5](/puppetlabs/cisco_ios/commit/79d7dd5cba4e04714dc77e131dbf5474af4194a0)
> 
>  new_instance[:key] = new_instance[:key].to_i unless new_instance[:key].nil? 
> ???

@tphoney Good call, we can remove these casts from providers and our function does the work for us!

**Comment by willmeek** [comment]
Rebased and good to merge

**Comment by willmeek** [comment]
Now using Puppet::Pops::Types for type checking

**Comment by willmeek** [comment]
Jenkins is green again

**Pull request merged**
