### PR TITLE
(maint) Discard unmodelled none value for snmp user privacy

### PR DESCRIPTION
**Pull request by willmeek**

### CODE REVIEW

**Comment by shermdog** [comment]
Should we consider adding `none` to the model?  Is that effectively an `unset`?

**Comment by willmeek** [comment]
I read it as being "this is not set" seems to be a default value that we get back from show snmp user when privacy isn't explicitly set with one of the values from our netdev stdlib enum.

I'm not sure if we can unset the privacy setting without removing and re-adding the user?

**Comment by tphoney** [comment]
none / unset is really inconsistent, we should raise a ticket on this. To make it consistent across the module, and put it on the backlog. Core methods in utility.rb will need to handle it.

**Comment by davidmalloncares** [comment]
FM-6882 covers what TP highlighted

**Pull request merged**
