### PR TITLE
(FM-6952) Add types and providers for configuring AAA

### PR DESCRIPTION
**Pull request by willmeek**
This includes
AAA Accounting
AAA Authentication
AAA Authorization
AAA New Model
AAA Session ID

### CODE REVIEW

**Comment by willmeek** [comment]
Adhoc pipeline https://jenkins-master-prod-1.delivery.puppetlabs.net/view/modules/view/networking/view/cisco_ios/view/adhoc/job/forge-module_puppetlabs-cisco_ios_intn-sys_full-pe-current-adhoc/34/

**Comment by shermdog** [comment]
Couple of questions / thoughts.

Do we want to use space separation for composite keys?  This would allow for underscores in values as well as be consistent with ciscopuppet.

Also I'm not sure how opinionated we want to be on multiple groups.  Currently the code behaves a bit inconsistent when multiple groups are configured.  Do we want to draw a line and say we only support single groups, or do something even crazier.

```
aaa accounting exec default start-stop group tacacs+ group under_group
aaa accounting commands 15 default start-stop group tacacs+

ios_aaa_accounting { 'commands_15_default': 
  accounting_service => 'commands',
  commands_enable_level => 15,
  accounting_list => 'default',
  accounting_status => 'start-stop',
  server_group => 'tacacs+',
  ensure => 'present',
}
ios_aaa_accounting { 'exec_default': 
  accounting_service => 'exec',
  accounting_list => 'default',
  accounting_status => 'start-stop',
  server_group => 'under_group',
  ensure => 'present',
}
```

**Comment by tphoney** [comment]
aside from @shermdog'd comments
image
👍

**Comment by willmeek** [comment]
Thanks :) , working on @shermdog comments, update PR soon

**Comment by willmeek** [comment]
Commit edited based on review comments:

- Composite name now uses spaces. I was previously unaware that we allowed spaces on names.
- server_group is now an array server_groups

**Comment by willmeek** [comment]
Adhoc pipeline acceptance tests

https://jenkins-master-prod-1.delivery.puppetlabs.net/view/modules/view/networking/view/cisco_ios/view/adhoc/job/forge-module_puppetlabs-cisco_ios_intn-sys_full-pe-current-adhoc/35/

**Comment by davidmalloncares** [comment]
needs a rebase @willmeek

**Pull request merged**
