### PR TITLE
(FM-7740) Add XE functionality for ios_aaa_accounting

### PR DESCRIPTION
**Pull request by willmeek**
Includes a test function to check if the device is XE, and test XE functionality accordingly

### CODE REVIEW

**Comment by willmeek** [comment]
Do not merge just yet, looking at example customer config

**Comment by willmeek** [comment]
Updated with 'update' based on customer config

**Comment by willmeek** [comment]
To be revisited as XE phase 2 epic

**Comment by DavidS** [comment]
Superseded by #347 as I can't push to this branch.

**Pull request closed without merging**
