### PR TITLE
(maint) adding in an os family fact value for allowing xe exclusions

### PR DESCRIPTION
**Pull request by Thomas-Franklin**

### CODE REVIEW

**Comment by willmeek** [comment]
I thought we were going to use os family as per
https://github.com/puppetlabs/cisco_ios/pull/297/files#diff-c62c6230a85c0d4fe78708e1864ce04bR349 ?

spec helper function
https://github.com/puppetlabs/cisco_ios/pull/297/files#diff-174f7dfb508155027cb4c3e9a1840591R6

**Comment by willmeek** [comment]
https://github.com/puppetlabs/cisco_ios/pull/297/files#diff-0ecdbe44ecb3380acfc8ff41d7aaa89cR67 to get the os family

**Comment by willmeek** [comment]
Function to get the os_family_type and compare to exclusions
https://github.com/puppetlabs/cisco_ios/pull/297/files#diff-0ecdbe44ecb3380acfc8ff41d7aaa89cR32

**Comment by willmeek** [comment]
Is it not worth cherry picking the non-content stuff from https://github.com/puppetlabs/cisco_ios/pull/297/files ?

**Comment by Thomas-Franklin** [comment]
Ah didn't see that, can get it cherrypicked across then instead

**Pull request merged**
