### PR TITLE
(maint) Update Spec Helper Acceptance to reflect new transport schema

### PR DESCRIPTION
**Pull request by willmeek**

### CODE REVIEW

**Comment by willmeek** [comment]
Acceptance tests currently correctly executing

**Comment by willmeek** [comment]
The credentials had a "successful" execution

```
Finished in 33 minutes 4 seconds (files took 13 minutes 22 seconds to load)
80 examples, 1 failure, 2 pending
```

1 failure which may or may not be related to earlier changes, to investigate

**Comment by willmeek** [comment]
Hold off on merge, ACL mode needs merged in again

```
Error: ios_acl_entry[test43 30]: Updating: Failed after 0.000613 seconds: undefined method `run_command_acl_mode' for #<Puppet::Transport::CiscoIos:0x00007fd65679fa20>
```

**Comment by willmeek** [comment]
Ready for merge

**Comment by DavidS** [comment]
are there no tests associated with the ACL changes?

**Comment by willmeek** [comment]
> are there no tests associated with the ACL changes?

An acceptance test which failed.

Otherwise, the transport class isn't covered by unit tests.

**Pull request merged**
